    [{
      "name": "Archer",
      "id": "109",
      "cost": "4",
      "side": "Corp",
      "identity": "The Weyland Consortium",
      "type": "ICE",
      "subtype": "Sentry - Destroyer",
      "loyalty": "2",
      "totalcost": 6,
      "strength": "6",
      "agendapoints": "0",
      "memory": "",
      "trash": "",
      "errata": "",
      "unique": "No",
      "text": "As an additional cost to rez Archer, the Corp must forfeit an agenda.<br \/>\n[Subroutine] The Corp gains 2 [Credits].<br \/>\n[Subroutine] Trash 1 program.<br \/>\n[Subroutine] Trash 1 program.<br \/>\n[Subroutine] End the run.",
      "set": "Core",
      "num": "101",
      "count": "2",
      "link": "0",
      "identitytop": "",
      "identitybottom": "",
      "flavor": "",
      "illustrator": "Mike Nesbitt",
      "furl": "archer-core",
      "numcomments": "11",
      "rating": "5",
      "GUID": "bc0f047c-01b1-427f-a439-d451eda01101",
      "img": ""
    }
  ]
